//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cleaning
    {
        public int CleaningID { get; set; }
        public int AviaryProcessID { get; set; }
        public string Description { get; set; }
    
        public virtual AviaryProcess AviaryProcess { get; set; }
    }
}
