//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWPF.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZooDBEntities : DbContext
    {
        public ZooDBEntities()
            : base("name=ZooDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Animal> Animal { get; set; }
        public virtual DbSet<AnimalKind> AnimalKind { get; set; }
        public virtual DbSet<AnimalProcess> AnimalProcess { get; set; }
        public virtual DbSet<Appointment> Appointment { get; set; }
        public virtual DbSet<Assay> Assay { get; set; }
        public virtual DbSet<Aviary> Aviary { get; set; }
        public virtual DbSet<AviaryProcess> AviaryProcess { get; set; }
        public virtual DbSet<Care> Care { get; set; }
        public virtual DbSet<Cleaning> Cleaning { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Feeding> Feeding { get; set; }
        public virtual DbSet<Repair> Repair { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Training> Training { get; set; }
        public virtual DbSet<Vaccination> Vaccination { get; set; }
    }
}
